version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./services/api
    env_file: .env
    depends_on: [db, redis]
    ports: ["8000:8000"]

  worker:
    build: ./services/worker
    env_file: .env
    depends_on: [db, redis]

  scheduler:
    build: ./services/scheduler
    env_file: .env
    depends_on: [api]

  frontend:
    build: ./services/frontend
    depends_on: [api]
    ports: ["4200:80"]

volumes:
  db-data:
