version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=sqlite:////app/data/market.db
    volumes:
      - ./backend:/app/backend
      - ./models:/models
      - ./data:/app/data
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: python:3.11-slim
    working_dir: /app
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    command: bash -lc "pip install streamlit requests && streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - backend
